on: push
name: Main Workflow
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.1.0
      with:
        host: "https://sonarcloud.io/"
        login: "6bef9992ee4e8a665cd1ada831027bbaad793fad"
        projectBaseDir: "/JokesWebApp/wwwroot/lib"
        projectKey: "my-custom-project"
        projectName: "my-custom-project-name"
        projectVersion: "v0.0.1"
